### ISSUE TITLE
raise NonMatchingChecksumError(resource.url, tmp_path)

### ISSUE THREAD

**Issue by mikechen66** [henrypowell87/AlexNet_TF2.0#1]
While I run the application, it generated the following error. Please help solve it. Thanks,

Using TensorFlow backend.
Downloading and preparing dataset oxford_flowers102/2.1.0 (download: 336.76 MiB, generated: 331.34 MiB, total: 668.11 MiB) to /home/mike/tensorflow_datasets/oxford_flowers102/2.1.0...
Extraction completed...: 0 file [06:49, ? file/s]1/1 [06:49<00:00, 409.67s/ url]
Dl Size...: 100%|███████████████████████████| 328/328 [06:49<00:00,  1.25s/ MiB]
Dl Completed...: 100%|█████████████████████████| 1/1 [06:49<00:00, 409.67s/ url]
Traceback (most recent call last):
  File "main.py", line 435, in <module>
    run_experiment(n, large_data_set=False, generator=True)
  File "main.py", line 401, in run_experiment
    data_train, data_test, data_val, info = load_data()
  File "main.py", line 77, in load_data
    data_train, info = tfds.load(name=data_set, split='test', with_info=True)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 53, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/registered.py", line 339, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 53, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 364, in download_and_prepare
    download_config=download_config)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1072, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 933, in _download_and_prepare
    dl_manager, **split_generators_kwargs):
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/image_classification/oxford_flowers102.py", line 109, in _split_generators
    "setid": os.path.join(_BASE_URL, "setid.mat"),
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 419, in download_and_extract
    return _map_promise(self._download_extract, url_or_urls)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 462, in _map_promise
    res = utils.map_nested(_wait_on_promise, all_promises)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 147, in map_nested
    for k, v in data_struct.items()
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 147, in <dictcomp>
    for k, v in data_struct.items()
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 161, in map_nested
    return function(data_struct)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 446, in _wait_on_promise
    return p.get()
  File "/home/mike/miniconda3/lib/python3.7/site-packages/promise/promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/promise/promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/promise/promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/mike/miniconda3/lib/python3.7/site-packages/promise/promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 306, in callback
    resource, download_dir_path, checksum, dl_size)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 261, in _handle_download_result
    raise NonMatchingChecksumError(resource.url, tmp_path)
tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz, downloaded to /home/mike/tensorflow_datasets/downloads/robots.ox.ac.uk_vgg_flowers_102_102flowersoWedSp98maBn1wypsDib6T-q2NVbO40fwvTflmPmQpY.tgz.tmp.9b82e0832fbf4576b0a2377b58b3c733/102flowers.tgz, has wrong checksum. This might indicate:
 * The website may be down (e.g. returned a 503 status code). Please check the url.
 * For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL. See https://github.com/tensorflow/datasets/issues/1482
 * The original datasets files may have been updated. In this case the TFDS dataset builder should be updated to use the new files and checksums. Sorry about that. Please open an issue or send us a PR with a fix.
 * If you're adding a new dataset, don't forget to register the checksums as explained in: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally

**Comment by mikechen66** [comment]
I solve the issue by installing tfds-nightly

### 1. Remove the downloaded files 

rm -rf ~/tensorflow_datasets/oxford_flowers102/
rm -rf ~/tensorflow_datasets/downloads

### 2. Install tfds-nightly

`$ pip --no-cache-dir install tfds-nightly`
