### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './file_names.npy'

### ISSUE THREAD

**Issue by mikechen66** [henrypowell87/AlexNet_TF2.0#2]
It shows FileNotFoundError: [Errno 2] No such file or directory. It seems that the application have not yet generated both file_names.npy and oh_labels.npy.  Shall you please provide file_names.npy and oh_labels.npy? 

Traceback (most recent call last):
  File "main.py", line 435, in <module>
    run_experiment(n, large_data_set=False, generator=True)
  File "main.py", line 410, in run_experiment
    train_images_file_names = np.load('/home/mike/Downloads/AlexNet_TF2.0/file_names.npy')
  File "/home/mike/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/Downloads/AlexNet_TF2.0/file_names.npy'

**Comment by henrypowell87** [comment]
Hi there,

Running the save_data function will generate these files for you. Although be warned that this function also does a considerable amount of data augmentation so you may want to comment out the augementation scripts.

Hope that helps.

**Comment by mikechen66** [comment]
Hi Henry:

Nice to get your feedback and appreciate your further help. I know that there are the lines of code for saving both _oh_labels_ and _file_names_.  I solved the problem but has other issues in the three chained messages. 

```
    # Save labels array to disk
    np.save(project_path + 'oh_labels', labels)

    # Save filenames array to disk
    file_names = np.array(file_names)
    np.save(project_path + 'file_names', file_names)
```

However, the path "/home/mike/Downloads/AlexNet_TF2.0" has no such two files ending with .npy.  Therefore, the system has thrown away the error as follows. 

_FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/Downloads/AlexNet_TF2.0/file_names.npy'_

Please see the detailed message. 

**$ python main.py**

Using TensorFlow backend.
2020-06-14 16:22:18.924300: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-06-14 16:22:18.981334: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2899885000 Hz
2020-06-14 16:22:18.982964: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5588caed31d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-14 16:22:18.983034: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-14 16:22:18.985964: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
tfds.core.DatasetInfo(
    name='oxford_flowers102',
    version=2.1.1,
    description='The Oxford Flowers 102 dataset is a consistent of 102 flower categories commonly occurring
in the United Kingdom. Each class consists of between 40 and 258 images. The images have
large scale, pose and light variations. In addition, there are categories that have large
variations within the category and several very similar categories.

The dataset is divided into a training set, a validation set and a test set.
The training set and validation set each consist of 10 images per class (totalling 1020 images each).
The test set consists of the remaining 6149 images (minimum 20 per class).',
    homepage='https://www.robots.ox.ac.uk/~vgg/data/flowers/102/',
    features=FeaturesDict({
        'file_name': Text(shape=(), dtype=tf.string),
        'image': Image(shape=(None, None, 3), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=102),
    }),
    total_num_examples=8189,
    splits={
        'test': 6149,
        'train': 1020,
        'validation': 1020,
    },
    supervised_keys=('image', 'label'),
    citation="""@InProceedings{Nilsback08,
       author = "Nilsback, M-E. and Zisserman, A.",
       title = "Automated Flower Classification over a Large Number of Classes",
       booktitle = "Proceedings of the Indian Conference on Computer Vision, Graphics and Image Processing",
       year = "2008",
       month = "Dec"
    }""",
    redistribution_info=,
)

WARNING: For consistency with `tfds.load`, the `tfds.show_examples` signature has been modified from (info, ds) to (ds, info).
The old signature is deprecated and will be removed. Please change your call to `tfds.show_examples(ds, info)`
WARNING: For consistency with `tfds.load`, the `tfds.show_examples` signature has been modified from (info, ds) to (ds, info).
The old signature is deprecated and will be removed. Please change your call to `tfds.show_examples(ds, info)`
Traceback (most recent call last):
  File "main.py", line 435, in <module>
    run_experiment(n, large_data_set=False, generator=True)
  File "main.py", line 410, in run_experiment
    train_images_file_names = np.load('/home/mike/Downloads/AlexNet_TF2.0/file_names.npy')
  File "/home/mike/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/Downloads/AlexNet_TF2.0/file_names.npy'

**Comment by mikechen66** [comment]
Hi Henry

I have gotten both oh_labels.npy and file_names.npy since I set the following large_data_set=True in the script of main_zero.py. 

```
# No. 230
def run_training(train_data, test_data, val_data, generator=True):
# No. 386
def run_experiment(n, large_data_set=False, generator=False):
# No.437
run_experiment(n, large_data_set=True, generator=False)
```

However, it throws the following error. 

_ValueError: zero-size array to reduction operation minimum which has no identity_

Please see the detailed message as follows. 

**$ python main_zero.py**

Using TensorFlow backend.
2020-06-14 17:06:23.472422: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-06-14 17:06:23.497213: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2899885000 Hz
2020-06-14 17:06:23.497718: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55612530a5b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-14 17:06:23.497754: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-14 17:06:23.497883: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
5100
[]
/home/mike/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/mike/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/mike/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/mike/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/mike/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Mean_accuracy=nan STD_accuracy=nan
Traceback (most recent call last):
  File "main_zero.py", line 439, in <module>
    run_experiment(n, large_data_set=True, generator=True)
  File "main_zero.py", line 432, in run_experiment
    print('Min_accuracy={}'.format(np.min(acc_scores)), 'Max_accuracy={}'.format(np.max(acc_scores)))
  File "<__array_function__ internals>", line 6, in amin
  File "/home/mike/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2793, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

**Comment by mikechen66** [comment]
After I re-execute the script of main.py, it gets through both oh_labels.npy and file_names.npy.  However, it generates the following error. 

_ValueError: Failed to find data adapter that can handle input: <class '__main__.DataGenerator'>, <class 'NoneType'>_

Please see the detailed running message as follows. 

**$ python main.py**

Using TensorFlow backend.
2020-06-14 17:08:22.643681: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-06-14 17:08:22.669155: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2899885000 Hz
2020-06-14 17:08:22.669438: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55855e3be220 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-14 17:08:22.669454: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-14 17:08:22.669529: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
tfds.core.DatasetInfo(
    name='oxford_flowers102',
    version=2.1.1,
    description='The Oxford Flowers 102 dataset is a consistent of 102 flower categories commonly occurring
in the United Kingdom. Each class consists of between 40 and 258 images. The images have
large scale, pose and light variations. In addition, there are categories that have large
variations within the category and several very similar categories.

The dataset is divided into a training set, a validation set and a test set.
The training set and validation set each consist of 10 images per class (totalling 1020 images each).
The test set consists of the remaining 6149 images (minimum 20 per class).',
    homepage='https://www.robots.ox.ac.uk/~vgg/data/flowers/102/',
    features=FeaturesDict({
        'file_name': Text(shape=(), dtype=tf.string),
        'image': Image(shape=(None, None, 3), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=102),
    }),
    total_num_examples=8189,
    splits={
        'test': 6149,
        'train': 1020,
        'validation': 1020,
    },
    supervised_keys=('image', 'label'),
    citation="""@InProceedings{Nilsback08,
       author = "Nilsback, M-E. and Zisserman, A.",
       title = "Automated Flower Classification over a Large Number of Classes",
       booktitle = "Proceedings of the Indian Conference on Computer Vision, Graphics and Image Processing",
       year = "2008",
       month = "Dec"
    }""",
    redistribution_info=,
)

WARNING: For consistency with `tfds.load`, the `tfds.show_examples` signature has been modified from (info, ds) to (ds, info).
The old signature is deprecated and will be removed. Please change your call to `tfds.show_examples(ds, info)`
WARNING: For consistency with `tfds.load`, the `tfds.show_examples` signature has been modified from (info, ds) to (ds, info).
The old signature is deprecated and will be removed. Please change your call to `tfds.show_examples(ds, info)`
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 62, 62, 3)         1092      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 3)         0         
_________________________________________________________________
batch_normalization (BatchNo (None, 31, 31, 3)         12        
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 21, 21, 256)       93184     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 10, 256)       0         
_________________________________________________________________
batch_normalization_1 (Batch (None, 10, 10, 256)       1024      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 8, 384)         885120    
_________________________________________________________________
batch_normalization_2 (Batch (None, 8, 8, 384)         1536      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 6, 6, 384)         1327488   
_________________________________________________________________
batch_normalization_3 (Batch (None, 6, 6, 384)         1536      
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 4, 4, 256)         884992    
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 2, 2, 256)         0         
_________________________________________________________________
batch_normalization_4 (Batch (None, 2, 2, 256)         1024      
_________________________________________________________________
flatten (Flatten)            (None, 1024)              0         
_________________________________________________________________
dense (Dense)                (None, 4096)              4198400   
_________________________________________________________________
dropout (Dropout)            (None, 4096)              0         
_________________________________________________________________
batch_normalization_5 (Batch (None, 4096)              16384     
_________________________________________________________________
dense_1 (Dense)              (None, 4096)              16781312  
_________________________________________________________________
dropout_1 (Dropout)          (None, 4096)              0         
_________________________________________________________________
batch_normalization_6 (Batch (None, 4096)              16384     
_________________________________________________________________
dense_2 (Dense)              (None, 1000)              4097000   
_________________________________________________________________
dropout_2 (Dropout)          (None, 1000)              0         
_________________________________________________________________
batch_normalization_7 (Batch (None, 1000)              4000      
_________________________________________________________________
dense_3 (Dense)              (None, 102)               102102    
=================================================================
Total params: 28,412,590
Trainable params: 28,391,640
Non-trainable params: 20,950
_________________________________________________________________
Traceback (most recent call last):
  File "main.py", line 438, in <module>
    run_experiment(n, large_data_set=False, generator=True)
  File "main.py", line 425, in run_experiment
    model = run_training(train_data, test_data, val_data)
  File "main.py", line 348, in run_training
    steps_per_epoch=steps_per_epoch)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 533, in _process_training_inputs
    adapter_cls = data_adapter.select_data_adapter(x, y)
  File "/home/mike/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 998, in select_data_adapter
    _type_name(x), _type_name(y)))
ValueError: Failed to find data adapter that can handle input: <class '__main__.DataGenerator'>, <class 'NoneType'>

**Comment by mikechen66** [comment]
If I delete all of the lines of code of the section of def save_data() from main.py and modify the last line of code to run_experiment(n, large_data_set=False, generator=False), the script of main.py can be successfully executed. It shows the results as follows. 

**0. Two Pictures**

It gives two pictures. 

**1. Description:**

> 2020-06-15 19:25:17.194634: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
> tfds.core.DatasetInfo(
>     name='oxford_flowers102',
>     version=2.1.1,
>     description='The Oxford Flowers 102 dataset is a consistent of 102 flower categories commonly occurring
> in the United Kingdom. Each class consists of between 40 and 258 images. The images have
> large scale, pose and light variations. In addition, there are categories that have large
> variations within the category and several very similar categories.

**2. Procedure**

The dataset is divided into a training set, a validation set and a test set.
The training set and validation set each consist of 10 images per class (totalling 1020 images each).
The test set consists of the remaining 6149 images (minimum 20 per class).',
```
    homepage='https://www.robots.ox.ac.uk/~vgg/data/flowers/102/',
    features=FeaturesDict({
        'file_name': Text(shape=(), dtype=tf.string),
        'image': Image(shape=(None, None, 3), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=102),
    }),
    total_num_examples=8189,
    splits={
        'test': 6149,
        'train': 1020,
        'validation': 1020,
    },
    supervised_keys=('image', 'label'),
    citation="""@InProceedings{Nilsback08,
       author = "Nilsback, M-E. and Zisserman, A.",
       title = "Automated Flower Classification over a Large Number of Classes",
       booktitle = "Proceedings of the Indian Conference on Computer Vision, Graphics and Image Processing",
       year = "2008",
       month = "Dec"
    }""",
    redistribution_info=,
)
```

**3. Model: "sequential"**
_________________________________________________________________
**Layer (type)                 Output Shape              Param #**   
=================================================================
conv2d (Conv2D)              (None, 62, 62, 3)         1092      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 3)         0         
_________________________________________________________________
batch_normalization (BatchNo (None, 31, 31, 3)         12        
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 21, 21, 256)       93184     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 10, 256)       0         
_________________________________________________________________
batch_normalization_1 (Batch (None, 10, 10, 256)       1024      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 8, 384)         885120    
_________________________________________________________________
batch_normalization_2 (Batch (None, 8, 8, 384)         1536      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 6, 6, 384)         1327488   
_________________________________________________________________
batch_normalization_3 (Batch (None, 6, 6, 384)         1536      
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 4, 4, 256)         884992    
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 2, 2, 256)         0         
_________________________________________________________________
batch_normalization_4 (Batch (None, 2, 2, 256)         1024      
_________________________________________________________________
flatten (Flatten)            (None, 1024)              0         
_________________________________________________________________
dense (Dense)                (None, 4096)              4198400   
_________________________________________________________________
dropout (Dropout)            (None, 4096)              0         
_________________________________________________________________
batch_normalization_5 (Batch (None, 4096)              16384     
_________________________________________________________________
dense_1 (Dense)              (None, 4096)              16781312  
_________________________________________________________________
dropout_1 (Dropout)          (None, 4096)              0         
_________________________________________________________________
batch_normalization_6 (Batch (None, 4096)              16384     
_________________________________________________________________
dense_2 (Dense)              (None, 1000)              4097000   
_________________________________________________________________
dropout_2 (Dropout)          (None, 1000)              0         
_________________________________________________________________
batch_normalization_7 (Batch (None, 1000)              4000      
_________________________________________________________________
dense_3 (Dense)              (None, 102)               102102    
=================================================================
Total params: 28,412,590
Trainable params: 28,391,640
Non-trainable params: 20,950

**4. Training** 

Train for 100 steps, validate for 11 steps
Epoch 1/90
 1/100 [..............................] - ETA: 7:11 - loss: 30827.0605 - acc: 0  2/100 [..............................] - ETA: 3:59 - loss: 31175.5654 - acc: 0  3/100 [..............................] - ETA: 2:56 - loss: 31587.4941 - acc: 0
....
